name: sns
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  app_ui:
    path: packages/app_ui
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  sns_client:
    path: packages/sns_client
  sns_mqtt_client:
    path: packages/sns_mqtt_client
  sns_repository:
    path: packages/sns_repository
  syncfusion_flutter_charts: ^26.1.41+1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
